#numpy

In [1]:
!pip install numpy

numPy stands for numerical python
it is a library used for --
* fast calculations
* arrays
* matrix operations
* machine learning computations

#Why NumPy is Used

Normal Python lists are slower for large numerical dat

In [10]:
import numpy as np
#creating a numpy array
arr=np.array([1,2,3,4,5])
print(arr)
#checking type
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
#array addtion
print(2*arr)
print(arr*2)
# for list
li=[1,2,3,4]
print(arr*2)
print(2*arr)
#in allabove cases outputs are same

[2 4 6 8]
[2 4 6 8]
[2 4 6 8]
[2 4 6 8]


In [12]:
# some mathematical prebuild functions in numpy
# for arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print("these are soome direct numpy opeartions on arrays")

15
5
1
3.0
these are soome direct numpy opeartions on arrays


In [15]:
arr2=np.array([[1,2,3],
               [1,2,3],
               [1,2,3]])
print(arr2)
print(arr2.shape)  #shape tell us about matrix order

[[1 2 3]
 [1 2 3]
 [1 2 3]]
(3, 3)


In [19]:
# zeroes and ones array
print(np.zeros((2,4)))

print(np.ones((2,3)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
#arrange array
arr3=np.arange(1,10)
print(arr3)
#reshape in any 2D array we want
arr4=arr3.reshape(3,3)
print(arr4)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


slicing and indexing same as normal array

In [27]:
#creating empty 2D array
#better to use zero array
emp_arr=np.empty((3,3))
print(emp_arr)
emp_arr[0][0]=1
print(emp_arr)
emp_arr=np.zeros((3,3))
print(emp_arr)

[[1.0e+000 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]
[[1.0e+000 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
# find the mid element
mid=len(arr3)//2
print(arr3[mid])

5


In [31]:
#for 2d array
print(arr4.shape)

(3, 3)


In [34]:
row_mid=arr4.shape[0]//2
col_mid=arr4.shape[1]//2
print(arr4[row_mid][col_mid])


5


Random modules

In [36]:
#printing random 8 integers from 1--20
a=np.random.randint(1,20,8)
print(a)

[ 5  5  4 12  4  5 18 15]


In [35]:
#printing random 3X3 matrix from range 1---100
import numpy as np
ar=np.random.randint(1,100,(3,3))
print(ar)

[[59 67 44]
 [23 73 31]
 [ 2 67 31]]


arr.shape---order of matrix
arr.ndim----dimension 1D or 2D
arr.size---- total elements in the array
arr.dtype---datatype of array

In [38]:
#flatten array ---2d --1d
print(arr4.flatten())
print(arr4)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#broadcasting
#doing opeartions on each elemenst on array

In [39]:
#boolean indexing
print(arr>3)
#print true on value greater than 3 anf false on left indexes

[False False False  True  True]


In [41]:
#filter measn if we want to print elements greagter than a value
print(arr[arr>3])

[4 5]


In [43]:
#fancy indexing
#we can print any element we want without loop
print(arr[[1,3,4]])

[2 4 5]


In [45]:
#axis concept
#print sum row wise and column wise
#axis=1  for row
#axis=0 for column
print(arr4)
print(np.sum(arr4,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]


In [46]:
#print col wise
print(np.sum(arr4,axis=0))

[12 15 18]


In [47]:
#print all element sum
print(np.sum(arr4,axis=None))


45


In [51]:
#specific row sum
#2nd r0w sum
print(np.sum(arr4[1,:]))

15


In [52]:
#first col sum
print(np.sum(arr4[:,0]))

12


In [54]:
#stacking of arrays
#combining varoius 1D array into 2D array row wise stack
a=np.array([1,2,3])
b=np.array([4,5,6])

print(np.vstack((a,b)))
#in 1D array stacking
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


10. Practice Questions
Create random 3x3 array
Find:
shape
ndim
size
Reshape 1D → 2D
Flatten 2D array
Filter elements greater than 50
Find row-wise sum
Find column-wise sum
Practice fancy indexing